#PowerShell command : [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("alex:password"))

### Login and get JWT token
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "alex",
  "password": "password"
}

> {%
    const token = JSON.parse(response.body).AuthToken;
    client.global.set("authToken", token);
%}


### Access protected endpoint with saved JWT token
GET http://localhost:8080/
Authorization: Bearer {{authToken}}
Content-Type: application/json
